title: Zheng Zhijie's Homepage
page-top-title: Zheng Zhijie
top-section-bg-text: Action is the only road to knowledge
home-subtitle: Zheng Zhijie&ensp;|&ensp;郑智杰
copyright-text: '&copy; Zheng Zhijie 2023-2025. All Rights Reserved.'
